# Generated by Django 4.2.30 on 2026-08-13 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('shoppable', 'Shoppable'), ('editorial', 'Editorial')], default='shoppable', max_length=12)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('founded', models.CharField(blank=True, max_length=12)),
                ('founder', models.CharField(blank=True, max_length=200)),
                ('designer', models.CharField(blank=True, max_length=200)),
                ('story', models.TextField(blank=True)),
                ('tier', models.CharField(blank=True, choices=[('luxury', 'Luxury Designer'), ('premium', 'Affordable Luxury'), ('contemporary', 'Contemporary')], max_length=14)),
                ('season', models.CharField(blank=True, max_length=120)),
                ('hero_image_url', models.URLField(blank=True, max_length=1000)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=300)),
                ('handle', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_display', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('color', models.CharField(blank=True, max_length=160)),
                ('occasion', models.CharField(choices=[('casual', 'Casual'), ('datenight', 'Date Night'), ('events', 'Events'), ('athleisure', 'Athleisure'), ('jewelry', 'Jewelry')], default='casual', max_length=16)),
                ('tier', models.CharField(blank=True, choices=[('luxury', 'Luxury Designer'), ('premium', 'Affordable Luxury'), ('contemporary', 'Contemporary')], max_length=14)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('image2_url', models.URLField(blank=True, max_length=1000)),
                ('available', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.brand')),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('brand', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('season', models.CharField(blank=True, max_length=120)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looks', to='catalog.brand')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('brand', 'index')},
            },
        ),
    ]
