# Generated by Django 4.2.30 on 2026-08-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='in_library',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
