# Generated by Django 4.2.30 on 2026-08-13 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand_dismissed_brand_in_library_brand_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('piece_tags', models.JSONField(blank=True, default=list)),
                ('model_id', models.CharField(blank=True, max_length=60)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='catalog.product')),
            ],
        ),
    ]
