# Generated by Django 4.2.30 on 2026-08-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_pieceattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=200, unique=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
