# Generated by Django 4.2.30 on 2026-08-13 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_nodeposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseLore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codes', models.JSONField(blank=True, default=list)),
                ('essence', models.CharField(blank=True, max_length=400)),
                ('history', models.JSONField(blank=True, default=list)),
                ('known', models.BooleanField(default=False)),
                ('model_id', models.CharField(blank=True, max_length=60)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lore', to='catalog.brand')),
            ],
        ),
    ]
