# Generated by Django 4.2.30 on 2026-08-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_houselore'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselore',
            name='directors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
