# Generated by Django 4.2.30 on 2026-08-13 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_houselore_directors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(blank=True, max_length=200)),
                ('season', models.CharField(blank=True, max_length=80)),
                ('year', models.CharField(blank=True, max_length=12)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('why', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('source', models.CharField(blank=True, max_length=60)),
                ('license', models.CharField(blank=True, max_length=80)),
                ('credit', models.CharField(blank=True, max_length=300)),
                ('model_id', models.CharField(blank=True, max_length=60)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='catalog.brand')),
            ],
            options={
                'ordering': ['brand', 'order'],
            },
        ),
    ]
