# Generated by Django 4.2.30 on 2026-08-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
