/* Editorial houses — followable, not shoppable. Verified metadata (Aug 2026).
   `looks` = real hotlinked look images from the house's OWN site where permitted;
   empty => the runway viewer shows labelled placeholder tiles. */
window.EDIT_EDITORIAL = [
  { key:"chanel", name:"Chanel", designer:"Matthieu Blazy", city:"Paris", founded:"1910", tier:"luxury",
    story:"Timeless Parisian elegance — tweed suits, quilted bags, pearls and the little black dress.",
    season:"Fall 2026 Haute Couture", looks:[] },
  { key:"dior", name:"Dior", designer:"Jonathan Anderson", city:"Paris", founded:"1946", tier:"luxury",
    story:"Opulent French couture rooted in the cinched-waist 'New Look' silhouette and romantic femininity.",
    season:"Fall 2026 Haute Couture", looks:[] },
  { key:"saintlaurent", name:"Saint Laurent", designer:"Anthony Vaccarello", city:"Paris", founded:"1961", tier:"luxury",
    story:"Sleek Parisian glamour — 'le smoking' tuxedos, sharp tailoring and rock-and-roll sensuality.",
    season:"Fall/Winter 2026", looks:[] },
  { key:"balenciaga", name:"Balenciaga", designer:"Pierpaolo Piccioli", city:"Paris", founded:"1919", tier:"luxury",
    story:"Avant-garde sculptural silhouettes merging couture craftsmanship with subversive modern volume.",
    season:"Fall 2026 Haute Couture", looks:[] },
  { key:"givenchy", name:"Givenchy", designer:"Sarah Burton", city:"Paris", founded:"1952", tier:"luxury",
    story:"Refined Parisian couture heritage reworked with tailored strength and painterly romance.",
    season:"Fall 2026 Ready-to-Wear", looks:[] },
  { key:"alexandermcqueen", name:"Alexander McQueen", designer:"Sean McGirr", city:"London", founded:"1992", tier:"luxury",
    story:"Dark British romanticism fusing sharp tailoring, subversive drama and provocative craft.",
    season:"Fall 2026 Ready-to-Wear", looks:[] },
  { key:"bottegaveneta", name:"Bottega Veneta", designer:"Louise Trotter", city:"Vicenza", founded:"1966", tier:"luxury",
    story:"Quiet Italian luxury — leather craft, the Intrecciato weave and understated refinement.",
    season:"Fall 2026 Ready-to-Wear", looks:[] },
  { key:"cos", name:"COS", designer:"Karin Gustafsson", city:"London", founded:"2007", tier:"contemporary",
    story:"Minimalist, architectural wardrobe staples with elevated everyday craftsmanship.",
    season:"Spring/Summer 2026", looks:[] },
  { key:"ashistudio", name:"Ashi Studio", designer:"Mohammed Ashi", city:"Paris", founded:"2007", tier:"luxury",
    story:"Saudi-founded couture — sculptural, architectural silhouettes with traditional craftsmanship.",
    season:"Fall 2026 Haute Couture", looks:[] },
  { key:"standingground", name:"Standing Ground", designer:"Michael Stewart", city:"London", founded:"2022", tier:"luxury",
    story:"Sculptural draping and architecturally precise jersey column gowns.",
    season:"Fall 2026 Haute Couture", looks:[] },
  { key:"lii", name:"LII", designer:"Zane Li", city:"New York", founded:"2023", tier:"premium",
    story:"Architecturally-minded womenswear pairing sport fabrics and minimalism with structural silhouettes.",
    season:"Spring 2026 Ready-to-Wear", looks:[] },
  { key:"insis", name:"INSIS", designer:null, city:null, founded:"2015", tier:"premium",
    story:"Timeless minimalist womenswear emphasizing refined texture and enduring quality over trends.",
    season:null, looks:[] },
  { key:"sonyamoda", name:"Sonya Moda", designer:"Sonya Mefaddi", city:"Sydney", founded:"2019", tier:"premium",
    story:"Australian occasion and resort wear — sculptural silhouettes, fluid draping, elegant timelessness.",
    season:null, looks:[] },
  { key:"charlottechesnais", name:"Charlotte Chesnais", designer:"Charlotte Chesnais", city:"Paris", founded:"2015", tier:"premium",
    story:"Sculptural French fine jewelry — classic hoops and rings reimagined with organic, irregular lines.",
    season:null, looks:[] },

  /* --- houses whose own imagery hotlinks: real looks --- */
  { key:"robertwun", name:"Robert Wun", designer:"Robert Wun", city:"London", founded:"2014", tier:"luxury",
    story:"Hong Kong-born, London-based couturier — cinematic tailoring and surrealist, sculptural silhouettes.",
    season:"Fall 2026 Haute Couture", looks:[
      "https://static.wixstatic.com/media/5aa3d0_7424d4f7ae58457e817dc4c7c5f57bff~mv2.jpg",
      "https://static.wixstatic.com/media/5aa3d0_f319ad0a53e34d2bb27ca7be2ed0baa8~mv2.jpg",
      "https://static.wixstatic.com/media/827c6d_46c7352362434c29a33a9795268e0876~mv2.jpg",
      "https://static.wixstatic.com/media/2245eb_da3785e91ca94691adef0b68765b5041~mv2.jpg",
      "https://static.wixstatic.com/media/2245eb_0878a77755f74e65847a813cd84cb693~mv2.jpg",
      "https://static.wixstatic.com/media/2245eb_5e05a05aec644e87a59963c6262bc837~mv2.jpg",
      "https://static.wixstatic.com/media/2245eb_1804de68ae014748b8fed9bcdfa35406~mv2.jpg"
    ] },
  { key:"nourhammour", name:"Nour Hammour", designer:"Nour Hammour & Erin Webb", city:"Paris", founded:"2013", tier:"premium",
    story:"Parisian luxury leather outerwear blending Parisian design with Turkish artisanal craft.",
    season:"Fall 2026", looks:[
      "https://cdn.shopify.com/s/files/1/0030/2946/7203/files/Roland_Ebony_Brown_1_Cropped.jpg?width=1600",
      "https://cdn.shopify.com/s/files/1/0030/2946/7203/files/JANE_1_Cropped.jpg?width=1600",
      "https://cdn.shopify.com/s/files/1/0030/2946/7203/files/Rios_Noir_Classique_4_Cropped.jpg?width=1600",
      "https://cdn.shopify.com/s/files/1/0030/2946/7203/files/Pia_Cajou_2_Cropped.jpg?width=1600",
      "https://cdn.shopify.com/s/files/1/0030/2946/7203/files/Passage_Noir_Classique_1_Cropped.jpg?width=1600",
      "https://cdn.shopify.com/s/files/1/0030/2946/7203/files/Winona_Mocha_Suede_1_Cropped.jpg?width=1600"
    ] }
];
